### ISSUE TITLE
Add this text to the landing jumbotron

### ISSUE THREAD

**Issue by niallrobinson** [met-office-lab/met-office-lab.github.io#159]
The text that was originally on the who we are page would work well on the jumbotron:

The Met Office Informatics Lab combines scientists, software engineers, and designers to create new things. We try to rapidly prototype non-business-as-usual ideas that allow people from within the Met Office (and beyond) to make our science and data useful.

The core group works as part of the UK's Met Office, which is one of the world's leading operational weather forecasters and climate change research institutes. However, we are really keen to work with anyone who has an interest and wants to collaborate on any of our projects.

**Comment by jacobtomlinson** [comment]
@RossJM did say something about adding a bit of text about who we are to that section. Perhaps this needs trimming down a little though otherwise it might spoil the simplicity of the jumbotron.
