### ISSUE TITLE
Design new theme

### ISSUE THREAD

**Issue by jacobtomlinson** [met-office-lab/met-office-lab.github.io#2]
The blog has been set up with an off the shelf theme just to get it off the ground.

But we really need to forge our own look and feel for it ourselves.

**Comment by msaunby** [comment]
True, but as we're getting our own dedicated designer soon it's perhaps best if we don't try and create our own style too soon.  Maybe we could try and adopt a 'no style' approach (like I dress?) for now.

**Comment by jacobtomlinson** [comment]
Agreed! I created this issue to keep track of the fact we need to do it. But we wont do it until we have a designer :).

**Comment by alberto-arribas** [comment]
Well done! .... Of course I need a crash course on the whole thing but I
will play with it during the weekend

**Comment by niallrobinson** [comment]
Ross is on this. We're gonna have go at tweaking the design properly tomorrow.

**Comment by niallrobinson** [comment]
Semi done - at least in the sense that i wrote a bunch of CSS to replace Pixyll .More refining to be done I'm sure
