### ISSUE TITLE
couple of niggles with new css theme

### ISSUE THREAD

**Issue by niallrobinson** [met-office-lab/met-office-lab.github.io#30]
moved from pixyll to bootstrap in this branch
https://github.com/met-office-lab/met-office-lab.github.io/tree/from_pixyll_to_bootstrap

however, I'm having problems with this section of './css/lab.scss':
```
.navbar-header {
	text-align: center; /* this doesn't work */
	display: block;
	bottom: 10px; /* this doesn't work and I don't know why */
}
```

The idea is that the nav bar sits to the left of the "test space" hexgon when there is enough room, but then drops down to be inline with below that hexagon as the browser narrows. Currently the maring at the bottom only seems to apply on the latter case.

In addition, the navbar items are meant to be centred as they're folded (a la the Pixyll theme) but they seem to be left aligned.

**Comment by jacobtomlinson** [comment]
I haven't got time to look at this today. My guess about `bottom` is that the [position](http://www.w3schools.com/css/css_positioning.asp) might not be set correctly.

**Comment by niallrobinson** [comment]
Thanks @jacobtomlinson. You're right to a certain extent - but the problem is that position has to be set as absolute, in order for it to overlap with the header graphic i.e. sit to the left of the hexagon logo.

**Comment by niallrobinson** [comment]
it was as known "feature" of bootstrap so I just worked round it
