### ISSUE TITLE
use hexagons as bullit points

### ISSUE THREAD

**Issue by niallrobinson** [met-office-lab/met-office-lab.github.io#44]
Change any bullet points to lab hexagons - might need to make a mini-font

**Comment by jacobtomlinson** [comment]
Can we get the hexagons in SVG format from Ross? It would make them nice and simple to use, especially if we want to do interesting animations and scalability stuff with them.

I think you can then use the SVG as a bullet point.

**Comment by jacobtomlinson** [comment]
Here is a nice example of SVG animations. I'm sure we could do somehting nice with the hexagons.

https://css-tricks.com/polylion/

**Comment by niallrobinson** [comment]
so cool - we should do that

**Comment by simonstanley** [comment]
This can be done, but is proving more trouble than its worth. Everyone happy for me to close?
