### ISSUE TITLE
fickering neon O

### ISSUE THREAD

**Issue by niallrobinson** [met-office-lab/met-office-lab.github.io#47]
@tpowellmeto  Idea for the O in the informatics lab logo to flicker on.

**Comment by jacobtomlinson** [comment]
Love it!

**Comment by jacobtomlinson** [comment]
Nice example, although could be improved on

http://codepen.io/rlemon/pen/kIiDE

**Comment by jacobtomlinson** [comment]
This is probably not going to be done any more now we are on v2.0.
