### ISSUE TITLE
Clean up relative paths and absolute paths with domain name

### ISSUE THREAD

**Issue by jacobtomlinson** [met-office-lab/met-office-lab.github.io#66]
Just a little winge, I've noticed relative path urls knocking around in the blog. Relative paths are bad practice and not to mention [gross](https://yoast.com/relative-urls-issues/), we need to stop using them.

We do have some absolute paths but most of them seem to have the full domain name at the beginning, this is also bad and causes a different set of problems. The main problem being during link testing, when you specify an absolute url with the domain name you are basically pointing externally to the master branch of the blog. If you create a page locally on your own branch which links to itself the link will fail tests because the page doesn't exist on master yet.

All internal links on the blog should begin with a `/` which means you are starting at the root of the current website and is therefore a valid internal link. 

@niallrobinson @simonstanley @alberto-arribas

**Comment by niallrobinson** [comment]
thanks - we obviously had a miscommunication at some point, because I thought you had told me to use relative paths so that it didn't matter if it was running on a local server or on the website. It should be rendered moot anyway when we get going with an imagebucket / gravitar

**Comment by jacobtomlinson** [comment]
Well moot for images but not for links to other pages.

**Comment by niallrobinson** [comment]
fair point
