### ISSUE TITLE
Cookie Policy

### ISSUE THREAD

**Issue by jacobtomlinson** [met-office-lab/met-office-lab.github.io#70]
As we are using Google Analytics we are storing cookies on peoples PCs.

Therefore by law we need a cookie policy.

**Comment by msaunby** [comment]
Suggest we use the GDS cookie policy, it covers exactly this use case.  https://www.gov.uk/help/cookies

**Comment by msaunby** [comment]
Better still, how about the Met Office policy http://www.metoffice.gov.uk/about-us/help/cookies
Suggest we copy the relevant parts rather than using a link as it might confuse as to whether it's our site's policy or not.
